version: '3.7'

services:
  web:
    build: .
    command: poetry run gunicorn --reload --bind 0.0.0.0:8000 manage:app
    working_dir: /app/app_name/
    volumes:
      - ./src/:/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: library/postgres:13.3
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data:
